### PR TITLE
Update android deps

### PR DESCRIPTION
**Pull request by otopba**

### CODE REVIEW

**Comment by dotdotcommadot** [comment]
Would be very nice to have this merged.

**Comment by dotdotcommadot** [comment]
@otopba ,This fix still hasn't been merged.
Can we assume this project is not maintained anymore?

**Comment by otopba** [comment]
@dotdotcommadot I think so =(
The last commit was a year ago

**Comment by jeroentrappers** [comment]
Sorry, I've been very busy. I'll try to make some time soon.

**Pull request merged**
